import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainSidebar from "@/components/sidebars/main";
import SecondarySidebar from "@/components/sidebars/secondary";
import { Sidebar, SidebarProvider } from "@/components/ui/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <Sidebar
            collapsible="icon"
            className="overflow-hidden [&>[data-sidebar=sidebar]]:flex-row"
          >
            <MainSidebar />
            <SecondarySidebar />
            {children}
          </Sidebar>
        </SidebarProvider>
      </body>
    </html>
  );
}
